# Change these first
owner: katana-network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: katana website
    url: https://katana.network
  - name: katana app
    url: https://app.katana.network
    maxResponseTime: 1000
  - name: katana api
    url: https://api.katana.network/health
    __dangerous__body_down_if_text_missing: '"status":"healthy"'
  - name: katana questing api
    url: https://questing-api.katana.network/health
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    maxResponseTime: 5000
  - name: vault rewards api
    url: https://vault-rewards-api.katana.network/api/v1/health
  - name: public rpc
    url: https://rpc.katana.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    # This expects the result to be false (meaning synced)
    __dangerous__body_down_if_text_missing: '"result":false'
  - name: zerion
    url: https://api.zerion.io/health
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  - name: balance api
    url: https://balance-api-gcp.polygon.technology/health-check
    __dangerous__body_down_if_text_missing: '"success":true'
  # --- External Dependencies ---

  - name: yearn api
    url: https://kong.yearn.farm/api/gql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"query":"{ __typename }"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: morpho api
    url: https://blue-api.morpho.org/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"query":"{ __typename }"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: sushiswap api
    url: https://api.sushi.com/price/v1/747474
    maxResponseTime: 5000

  - name: coingecko api
    url: https://api.coingecko.com/api/v3/ping
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: merkl api
    url: https://api.merkl.xyz/v4/tokens/reward/747474
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: trails (sequence)
    url: https://trails-api.sequence.app/rpc/Trails/GetIntent
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"intentId":"health-check-00000000-0000-0000-0000-000000000000"}'
    expectedStatusCodes:
      - 200
      - 400
    maxResponseTime: 5000

  - name: configcat cdn
    url: https://cdn-global.configcat.com
    expectedStatusCodes:
      - 200
      - 403
    maxResponseTime: 3000

  # --- Chain Health (Katana 747474) ---

  # Verify chain ID is correct (0xb6862 = 747474)
  - name: katana rpc - chain id
    url: https://rpc.katana.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"0xb67d2"'
    maxResponseTime: 5000

  # Verify chain returns a block number (node has data)
  - name: katana rpc - block number
    url: https://rpc.katana.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"result":"0x'
    maxResponseTime: 5000

  # Conduit RPC directly (bypasses eRPC) - uses GitHub Secret
  - name: conduit katana rpc
    url: $CONDUIT_KATANA_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"0xb67d2"'
    maxResponseTime: 5000

  # Block explorer - if it loads, chain data pipeline is working
  - name: katanascan explorer
    url: https://katanascan.com
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katana.network
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: katana status
  introTitle: "Uptime and monitor for critical katana components"
  introMessage: This status page monitors key components necessary for the katana ecosystem and app.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
