# Change these first
owner: katana-network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: katana website
    url: https://katana.network
  - name: katana app
    url: https://app.katana.network
  - name: katana api
    url: https://api-staging.katana.network
  - name: vault rewards api
    url: https://vault-rewards-api.katana.network/api/v1/health
  - name: public rpc
    url: https://rpc.katana.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    # This expects the result to be false (meaning synced)
    __dangerous__body_down_if_text_missing: '"result":false'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katana.network
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: katana status
  introTitle: "Uptime and monitor for critical katana components"
  introMessage: This status page monitors key components necessary for the katana ecosystem and app.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
