# Change these first
owner: katana-network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: katana website
    url: https://katana.network
  - name: katana app
    url: https://app.katana.network
    maxResponseTime: 1000
  - name: katana api
    url: https://api.katana.network/health
    __dangerous__body_down_if_text_missing: '"status":"healthy"'
  - name: katana questing api
    url: https://questing-api.katana.network/health
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    maxResponseTime: 5000
  - name: vault rewards api
    url: https://vault-rewards-api.katana.network/api/v1/health
  - name: public rpc
    url: https://rpc.katana.network
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
    expectedStatusCodes:
      - 200
    # This expects the result to be false (meaning synced)
    __dangerous__body_down_if_text_missing: '"result":false'
  - name: zerion
    url: https://api.zerion.io/health
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  - name: balance api
    url: https://balance-api-gcp.polygon.technology/health-check
    __dangerous__body_down_if_text_missing: '"success":true'
#  - name: yearn api
#    url:
#  - name: morpho api
#    url:
#  - name: leaderboard api
#    url: https://leaderboard.katana.network/api/_health/live

status-website:
  cname: status.katana.network
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/katana-network/status/master/assets/katana-icon.svg
  name: katana status
  theme: dark
  introTitle: "**Katana** Status"
  introMessage: Real-time monitoring for the Katana ecosystem — app, APIs, RPC, and external dependencies.
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.katana.network
    - title: Website
      href: https://katana.network
  css: |
    /* Katana Brand Theme — colors from Figma design tokens */
    :root {
      --body-background-color: #070B20;       /* Flats/Dark Ink */
      --body-text-color: #DADCE7;             /* white/100 */
      --card-background-color: #0D1126;       /* dark-blue-2/800 */
      --nav-background-color: #0D1126;        /* dark-blue-2/800 */
      --nav-border-bottom-color: rgba(218, 220, 231, 0.08); /* white/8 */
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }

    /* Links and interactive elements — katana blue */
    a {
      color: #0550DB;
    }
    a:hover {
      color: #4B8AFF;
    }

    /* Up/operational indicators — katana green */
    .color-dot.up, .badge.up {
      background-color: #0DFFAA !important;
    }
    .up .color-dot {
      background-color: #0DFFAA !important;
    }

    /* Down/error indicators — katana red */
    .color-dot.down, .badge.down {
      background-color: #F12211 !important;
    }
    .down .color-dot {
      background-color: #F12211 !important;
    }

    /* Degraded indicators — katana yellow/spark */
    .color-dot.degraded, .badge.degraded {
      background-color: #F6FF0D !important;
    }
    .degraded .color-dot {
      background-color: #F6FF0D !important;
    }

    /* Card and section styling */
    .card, section {
      border: 1px solid rgba(218, 220, 231, 0.04); /* white/4 border-subtle */
      border-radius: 16px;
    }

    /* Nav styling */
    nav, .navbar {
      border-bottom: 1px solid rgba(218, 220, 231, 0.08) !important;
    }

    /* Muted/secondary text */
    .text-muted, .text-secondary, small, .description {
      color: rgba(218, 220, 231, 0.48); /* white/48 */
    }

    /* Chart colors */
    .chart-up, .graph-up {
      stroke: #0DFFAA;
      fill: rgba(13, 255, 170, 0.12);
    }

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
